### ISSUE TITLE
Not working sub menues of ARD Audiothek

### ISSUE THREAD

**Issue by hukipola** [mzedd/LMS-ARD-Audiothek-Plugin#15]
Bug description:
When I start the App from the android app or from the webinterface I'm just able to reach the first layer of selection. 
I can choose between: 
Suche
Entdecken
Sender
Rubriken 

But nothing from those does anything. 

My setup:
Logitech Media Server Version: 8.2.0 
raspi 3 +

**Comment by mzedd** [comment]
Hi hukipola,
sorry for my late reply. Could you please provide a copy of your LMS server.log when starting the app? Which android app are you using to control the LMS?

**Comment by mzedd** [comment]
Hi @hukipola,
does the app work for you now or is the problem still there?
