### ISSUE TITLE
An invisible Podcasts nach Rubrik duplicate entry is located within start menu

### ISSUE THREAD

**Issue by bungh0l10** [mzedd/LMS-ARD-Audiothek-Plugin#26]
Hi @mzedd,
as per title I just found a small quirk, which is invisible to those using material skin but noticeable using "standard" LMS web-interface as well as navigating through physical SB devices. Basically an empty line gets displayed which links to "Podcasts nach Rubrik". 

![grafik](https://github.com/mzedd/LMS-ARD-Audiothek-Plugin/assets/77304055/304ce2df-3d15-4014-9563-ccdb5c4bbd55)

edit...
And I think this is caused because ARD introduced the podcast categories without a section title in addition to the already existing "Podcasts nach Rubrik" section.
![grafik](https://github.com/mzedd/LMS-ARD-Audiothek-Plugin/assets/77304055/4a0ad301-3d42-467a-977a-55bc9d3d0e4d)

cheers

**Comment by mzedd** [comment]
Fixed by #28. Thanks @bungh0l10.
